Feat/car for rent
tringuyennfq/CarForRent pull request #2
Opened 2022-05-18 10:42 UTC by tringuyennfq

2022-05-18 12:50 UTC, tinhlesc commented
@tringuyennfq please refer how to put the name of folder from Khoa Tran.
You should put the name like: Controller, Bootstrap, Database or something like that.

2022-05-19 02:59 UTC, bangdinhnfq requested changes

2022-05-19 02:59 UTC, bangdinhnfq commented on src/view/login.php
> +<?php
Don't need. Should remove.

2022-05-19 02:59 UTC, bangdinhnfq commented on src/view/login.php
> +        <p class="mt-5 mb-3 text-muted">&copy; 2022 <?php echo $name; ?></p>
It should be 
```
<?= echo $name; ?>
```

2022-05-19 02:59 UTC, bangdinhnfq commented on src/view/login.php
> +        <p class="mt-5 mb-3 text-muted">&copy; 2022 <?php echo $name; ?></p>
It should be 
```
<?= echo $name; ?>
```

2022-05-19 02:59 UTC, bangdinhnfq commented on src/bootstrap/View.php
> +        return str_replace('{{content}}', $viewContent, $layoutContent);
content must be variable

2022-05-19 02:59 UTC, bangdinhnfq commented on src/bootstrap/View.php
> +        return str_replace('{{content}}', $viewContent, $layoutContent);
content must be variable

2022-05-19 02:59 UTC, bangdinhnfq commented on src/bootstrap/View.php
> +        include_once Application::$ROOT_DIR . "/src/view/layouts/main.php";
Should define as a constant

2022-05-19 02:59 UTC, bangdinhnfq commented on src/bootstrap/View.php
> +        include_once Application::$ROOT_DIR . "/src/view/layouts/main.php";
Should define as a constant

2022-05-19 02:59 UTC, bangdinhnfq commented on src/bootstrap/View.php
> +        include_once Application::$ROOT_DIR . "/src/view/$view.php";
Should define as a constant

2022-05-19 02:59 UTC, bangdinhnfq commented on src/bootstrap/View.php
> +        include_once Application::$ROOT_DIR . "/src/view/$view.php";
Should define as a constant

2022-05-19 02:59 UTC, bangdinhnfq commented on src/database/DatabaseConnect.php
> +                echo "Connected successfully";
Remove echo

2022-05-19 02:59 UTC, bangdinhnfq commented on src/database/DatabaseConnect.php
> +                echo "Connected successfully";
Remove echo

2022-05-19 02:59 UTC, bangdinhnfq commented on src/database/DatabaseConnect.php
> +                echo "Connection failed: " . $e->getMessage();
Should handle exception

2022-05-19 02:59 UTC, bangdinhnfq commented on src/database/DatabaseConnect.php
> +                echo "Connection failed: " . $e->getMessage();
Should handle exception

2022-05-19 02:59 UTC, bangdinhnfq commented on public/index.php
> +ini_set('display_errors', '1');
Remove debug code

2022-05-19 02:59 UTC, bangdinhnfq commented on public/index.php
> +ini_set('display_errors', '1');
Remove debug code

2022-05-24 02:55 UTC, bangdinhnfq requested changes

2022-05-24 02:55 UTC, bangdinhnfq commented on src/view/login.php
> +<?php
Don't need. Should remove.

2022-05-24 02:55 UTC, bangdinhnfq commented on Tests/Tringuyen/CarForRent/Model/UserTest.php
> +}
EOL

2022-05-24 02:55 UTC, bangdinhnfq commented on src/Controller/UserLoginController.php
> +//    public function handleLogin()
Remove unused code

2022-05-24 02:55 UTC, bangdinhnfq commented on src/Exception/LoginException.php
> +}
EOL

2022-06-06 10:01 UTC, merged